spring:
  application:
    name: es-service
  banner:
    location: classpath:banner/banner.txt
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.32.100:8848
  redis:
    host: 192.168.32.100
    port: 6379
    database: 0
    password: 1018
  rabbitmq:
    host: 192.168.32.100
    port: 5672
    virtual-host: /
    username: imooc
    password: ENC(lsfCPe1pNl8A+ady3fqXYg==)
    # 消费者信息确认模式修改为手动
    listener:
      simple:
        acknowledge-mode: manual
# 服务器应用配置
server:
  port: 2001
  tomcat:
    uri-encoding: UTF-8
    # 这个配置设置 tomcat 服务器上传文件的时候吞吐量校验 默认超过 2M 的文件不会被捕获 -1 代表不校验文件大小
    max-swallow-size: -1
#  配置 jasypt 加密信息
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: Sharn