spring:
  datasource:                                     # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://192.168.32.100:3306/imooc_hire_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1018
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.32.100:8848
  # redis 配置 提升 app 端查询的时候接口响应的 QPS
  redis:
    host: 192.168.32.100
    port: 6379
    database: 0
    password: 1018
  rabbitmq:
    host: 192.168.32.100
    port: 5672
    virtual-host: /
    username: imooc
    password: ENC(lsfCPe1pNl8A+ady3fqXYg==)
    # 消费者信息确认模式修改为手动
    listener:
      simple:
        acknowledge-mode: manual
        # MQ 消费限流（每次获取 n 条数据 确认之后重新获取）
        prefetch: 2  # 每次从队列中获取 2 条消息确认之后再从队列中重新获取 相当于每次获取两条 确认之后再获取两条

# 配置mybatis-plus 信息
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    # 取消项目启动加载 banner
    banner: false
    db-config:
      # 项目生成的主键策略 （雪花算法）
      id-type: assign_id

# jasypt 加密密钥和加密算法（默认）
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: Sharn

# 配置 seata 分布式事务相关信息
seata:
  enabled: true
  # 事务组的名称 这个是可以自定义的
  tx-service-group: imooc_tx_group
  service:
    vgroup-mapping:
      imooc_tx_group: SEATA_GROUP
    grouplist:
      # 配置 seata 所在事务组服务端 ip 地址
      SEATA_GROUP: 192.168.32.100:8091
  config:
    nacos:
      server-addr: 192.168.32.100:8848
      username: nacos
      password: nacos
  registry:
    nacos:
      server-addr: 192.168.32.100:8848
      username: nacos
      password: nacos

# canal 相关配置
canal:
  destination: imooc
  server: 192.168.32.100:11111
  user-name: root
  password: 1018

# 避免 canal 打印过多信息
logging:
  level:
    top.javatool.canal.client: warn