spring:
  application:
    name: user-service
  banner:
    location: classpath:banner/banner.txt
  cloud:
    nacos:
      server-addr: 192.168.32.100:8848
  #  数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.32.100:3306/imooc_hire_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1018
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000            # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                      # 最小连接数
      maximum-pool-size: 20                # 最大连接数
      auto-commit: true                    # 自动提交
      idle-timeout: 600000                 # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP        # 连接池的名字
      max-lifetime: 18000000               # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1

server:
  port: 7001
  tomcat:
    uri-encoding: UTF-8
    # 这个配置设置 tomcat 服务器上传文件的时候吞吐量校验 默认超过 2M 的文件不会被捕获 -1 代表不校验文件大小
    max-swallow-size: -1


# 配置mybatis-plus 信息
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    # 取消项目启动加载 banner
    banner: false
    db-config:
      # 项目生成的主键策略 （雪花算法）
      id-type: assign_id
      # 修改更新策略，解决的问题是前端传递的信息为空字符串时 不更新数据库中原有的数据
      update-strategy: not_empty